// Generated by FlutterFire CLI. To regenerate:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=markly-agp --platforms=android,windows
//
// The Windows appId requires a Firebase Web App registered in the project.
// Run the command above and commit the regenerated file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure --project=markly-agp --platforms=android,windows',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4yQgMAl-gurqhy0zZ-Uhup_B0_t_QRsI',
    appId: '1:169364452296:android:e37c03d83c887f470f06fd',
    messagingSenderId: '169364452296',
    projectId: 'markly-agp',
    storageBucket: 'markly-agp.firebasestorage.app',
  );

  // TODO: replace appId with the real Firebase Web App id.
  // Get it from: Firebase Console → Project Settings → Web apps → App ID
  // Or run: flutterfire configure --project=markly-agp --platforms=android,windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9dxGQIwtXZ78jHii-yK8z-Vh3k_TTbOU',
    appId: '1:169364452296:web:c2498ae40cc60cb30f06fd',
    messagingSenderId: '169364452296',
    projectId: 'markly-agp',
    authDomain: 'markly-agp.firebaseapp.com',
    storageBucket: 'markly-agp.firebasestorage.app',
    measurementId: 'G-LZ4FJJWJWX',
  );
}
